name = "siwe-oidc" # your project name
compatibility_date = "2023-05-30"

type = "javascript"
account_id = "" # your account id
# zone_id = ""
workers_dev = false

kv_namespaces = [
    # fill in id and optionally preview_id for kv
    { binding = "SIWE_OIDC", id = "", preview_id = "" }
]

[vars]
WORKERS_RS_VERSION = "0.0.9"
BASE_URL = "https://siweoidc.spruceid.xyz"
# ETH_PROVIDER = ""

[durable_objects]
bindings = [
  { name = "SIWE-OIDC-CODES", class_name = "DOCodes" }
]

[[migrations]]
tag = "v1"
new_classes = ["DOCodes"]

[build]
command = "mkdir -p static/_worker.js && (cd js/ui && npm ci && npm run build) && cargo install -q worker-build && worker-build --release && cp -r build/worker/* static/_worker.js/ && mv static/_worker.js/shim.mjs static/_worker.js/index.js"
